<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class KabkotaSeeder extends Seeder
{

    public function run()
    {
        $array=[
            [ 'kd_kabkota' => '010100',  'nama_kabkota' => 'Kab. Kepulauan Seribu', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '016000',  'nama_kabkota' => 'Kota Jakarta Pusat', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '016100',  'nama_kabkota' => 'Kota Jakarta Utara', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '016200',  'nama_kabkota' => 'Kota Jakarta Barat', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '016300',  'nama_kabkota' => 'Kota Jakarta Selatan', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '016400',  'nama_kabkota' => 'Kota Jakarta Timur', 'id_provinsi' => '1', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '020500',  'nama_kabkota' => 'Kab. Bogor', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '020600',  'nama_kabkota' => 'Kab. Sukabumi', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '020700',  'nama_kabkota' => 'Kab. Cianjur', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '020800',  'nama_kabkota' => 'Kab. Bandung', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021000',  'nama_kabkota' => 'Kab. Sumedang', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021100',  'nama_kabkota' => 'Kab. Garut', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021200',  'nama_kabkota' => 'Kab. Tasikmalaya', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021400',  'nama_kabkota' => 'Kab. Ciamis', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021500',  'nama_kabkota' => 'Kab. Kuningan', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021600',  'nama_kabkota' => 'Kab. Majalengka', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021700',  'nama_kabkota' => 'Kab. Cirebon', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021800',  'nama_kabkota' => 'Kab. Indramayu', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '021900',  'nama_kabkota' => 'Kab. Subang', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '022000',  'nama_kabkota' => 'Kab. Purwakarta', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '022100',  'nama_kabkota' => 'Kab. Karawang', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '022200',  'nama_kabkota' => 'Kab. Bekasi', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '022300',  'nama_kabkota' => 'Kab. Bandung Barat', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '022500',  'nama_kabkota' => 'Kab. Pangandaran', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026000',  'nama_kabkota' => 'Kota Bandung', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026100',  'nama_kabkota' => 'Kota Bogor', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026200',  'nama_kabkota' => 'Kota Sukabumi', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026300',  'nama_kabkota' => 'Kota Cirebon', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026500',  'nama_kabkota' => 'Kota Bekasi', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026600',  'nama_kabkota' => 'Kota Depok', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026700',  'nama_kabkota' => 'Kota Cimahi', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026800',  'nama_kabkota' => 'Kota Tasikmalaya', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '026900',  'nama_kabkota' => 'Kota Banjar', 'id_provinsi' => '2', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030100',  'nama_kabkota' => 'Kab. Cilacap', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030200',  'nama_kabkota' => 'Kab. Banyumas', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030300',  'nama_kabkota' => 'Kab. Purbalingga', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030400',  'nama_kabkota' => 'Kab. Banjarnegara', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030500',  'nama_kabkota' => 'Kab. Kebumen', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030600',  'nama_kabkota' => 'Kab. Purworejo', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030700',  'nama_kabkota' => 'Kab. Wonosobo', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030800',  'nama_kabkota' => 'Kab. Magelang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '030900',  'nama_kabkota' => 'Kab. Boyolali', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031000',  'nama_kabkota' => 'Kab. Klaten', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031100',  'nama_kabkota' => 'Kab. Sukoharjo', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031200',  'nama_kabkota' => 'Kab. Wonogiri', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031300',  'nama_kabkota' => 'Kab. Karanganyar', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031400',  'nama_kabkota' => 'Kab. Sragen', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031500',  'nama_kabkota' => 'Kab. Grobogan', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031600',  'nama_kabkota' => 'Kab. Blora', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031700',  'nama_kabkota' => 'Kab. Rembang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031800',  'nama_kabkota' => 'Kab. Pati', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '031900',  'nama_kabkota' => 'Kab. Kudus', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032000',  'nama_kabkota' => 'Kab. Jepara', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032100',  'nama_kabkota' => 'Kab. Demak', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032200',  'nama_kabkota' => 'Kab. Semarang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032300',  'nama_kabkota' => 'Kab. Temanggung', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032400',  'nama_kabkota' => 'Kab. Kendal', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032500',  'nama_kabkota' => 'Kab. Batang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032600',  'nama_kabkota' => 'Kab. Pekalongan', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032700',  'nama_kabkota' => 'Kab. Pemalang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032800',  'nama_kabkota' => 'Kab. Tegal', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '032900',  'nama_kabkota' => 'Kab. Brebes', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036000',  'nama_kabkota' => 'Kota Magelang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036100',  'nama_kabkota' => 'Kota Surakarta', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036200',  'nama_kabkota' => 'Kota Salatiga', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036300',  'nama_kabkota' => 'Kota Semarang', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036400',  'nama_kabkota' => 'Kota Pekalongan', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '036500',  'nama_kabkota' => 'Kota Tegal', 'id_provinsi' => '3', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '040100',  'nama_kabkota' => 'Kab. Bantul', 'id_provinsi' => '4', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '040200',  'nama_kabkota' => 'Kab. Sleman', 'id_provinsi' => '4', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '040300',  'nama_kabkota' => 'Kab. Gunung Kidul', 'id_provinsi' => '4', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '040400',  'nama_kabkota' => 'Kab. Kulon Progo', 'id_provinsi' => '4', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '046000',  'nama_kabkota' => 'Kota Yogyakarta', 'id_provinsi' => '4', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050100',  'nama_kabkota' => 'Kab. Gresik', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050200',  'nama_kabkota' => 'Kab. Sidoarjo', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050300',  'nama_kabkota' => 'Kab. Mojokerto', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050400',  'nama_kabkota' => 'Kab. Jombang', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050500',  'nama_kabkota' => 'Kab. Bojonegoro', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050600',  'nama_kabkota' => 'Kab. Tuban', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050700',  'nama_kabkota' => 'Kab. Lamongan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050800',  'nama_kabkota' => 'Kab. Madiun', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '050900',  'nama_kabkota' => 'Kab. Ngawi', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051000',  'nama_kabkota' => 'Kab. Magetan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051100',  'nama_kabkota' => 'Kab. Ponorogo', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051200',  'nama_kabkota' => 'Kab. Pacitan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051300',  'nama_kabkota' => 'Kab. Kediri', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051400',  'nama_kabkota' => 'Kab. Nganjuk', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051500',  'nama_kabkota' => 'Kab. Blitar', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051600',  'nama_kabkota' => 'Kab. Tulungagung', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051700',  'nama_kabkota' => 'Kab. Trenggalek', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051800',  'nama_kabkota' => 'Kab. Malang', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '051900',  'nama_kabkota' => 'Kab. Pasuruan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052000',  'nama_kabkota' => 'Kab. Probolinggo', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052100',  'nama_kabkota' => 'Kab. Lumajang', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052200',  'nama_kabkota' => 'Kab. Bondowoso', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052300',  'nama_kabkota' => 'Kab. Situbondo', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052400',  'nama_kabkota' => 'Kab. Jember', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052500',  'nama_kabkota' => 'Kab. Banyuwangi', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052600',  'nama_kabkota' => 'Kab. Pamekasan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052700',  'nama_kabkota' => 'Kab. Sampang', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052800',  'nama_kabkota' => 'Kab. Sumenep', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '052900',  'nama_kabkota' => 'Kab. Bangkalan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056000',  'nama_kabkota' => 'Kota Surabaya', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056100',  'nama_kabkota' => 'Kota Malang', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056200',  'nama_kabkota' => 'Kota Madiun', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056300',  'nama_kabkota' => 'Kota Kediri', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056400',  'nama_kabkota' => 'Kota Mojokerto', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056500',  'nama_kabkota' => 'Kota Blitar', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056600',  'nama_kabkota' => 'Kota Pasuruan', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056700',  'nama_kabkota' => 'Kota Probolinggo', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '056800',  'nama_kabkota' => 'Kota Batu', 'id_provinsi' => '5', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060100',  'nama_kabkota' => 'Kab. Aceh Besar', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060200',  'nama_kabkota' => 'Kab. Pidie', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060300',  'nama_kabkota' => 'Kab. Aceh Utara', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060400',  'nama_kabkota' => 'Kab. Aceh Timur', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060500',  'nama_kabkota' => 'Kab. Aceh Tengah', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060600',  'nama_kabkota' => 'Kab. Aceh Barat', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060700',  'nama_kabkota' => 'Kab. Aceh Selatan', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '060800',  'nama_kabkota' => 'Kab. Aceh Tenggara', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061100',  'nama_kabkota' => 'Kab. Simeulue', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061200',  'nama_kabkota' => 'Kab. Bireuen', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061300',  'nama_kabkota' => 'Kab. Aceh Singkil', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061400',  'nama_kabkota' => 'Kab. Aceh Tamiang', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061500',  'nama_kabkota' => 'Kab. Nagan Raya', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061600',  'nama_kabkota' => 'Kab. Aceh Jaya', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061700',  'nama_kabkota' => 'Kab. Aceh Barat Daya', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061800',  'nama_kabkota' => 'Kab. Gayo Lues', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '061900',  'nama_kabkota' => 'Kab. Bener Meriah', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '062000',  'nama_kabkota' => 'Kab. Pidie Jaya', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '066000',  'nama_kabkota' => 'Kota Sabang', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '066100',  'nama_kabkota' => 'Kota Banda Aceh', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '066200',  'nama_kabkota' => 'Kota Lhokseumawe', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '066300',  'nama_kabkota' => 'Kota Langsa', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '066400',  'nama_kabkota' => 'Kab. Sabussalam', 'id_provinsi' => '6', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070100',  'nama_kabkota' => 'Kab. Deli Serdang', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070200',  'nama_kabkota' => 'Kab. Langkat', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070300',  'nama_kabkota' => 'Kab. Karo', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070400',  'nama_kabkota' => 'Kab. Simalungun', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070500',  'nama_kabkota' => 'Kab. Dairi', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070600',  'nama_kabkota' => 'Kab. Asahan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070700',  'nama_kabkota' => 'Kab. Labuhan Batu', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070800',  'nama_kabkota' => 'Kab. Tapanuli Utara', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '070900',  'nama_kabkota' => 'Kab. Tapanuli Tengah', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071000',  'nama_kabkota' => 'Kab. Tapanuli Selatan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071100',  'nama_kabkota' => 'Kab. Nias', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071500',  'nama_kabkota' => 'Kab. Mandailing Natal', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071600',  'nama_kabkota' => 'Kab. Toba Samosir', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071700',  'nama_kabkota' => 'Kab. Nias Selatan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071800',  'nama_kabkota' => 'Kab. Pak pak Bharat', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '071900',  'nama_kabkota' => 'Kab. Humbang Hasudutan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072000',  'nama_kabkota' => 'Kab. Samosir', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072100',  'nama_kabkota' => 'Kab. Serdang Bedagai', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072200',  'nama_kabkota' => 'Kab. Batubara', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072300',  'nama_kabkota' => 'Kab. Padang Lawas utara', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072400',  'nama_kabkota' => 'Kab. Padang Lawas', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072500',  'nama_kabkota' => 'Kab. Labuhan Batu Utara', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072600',  'nama_kabkota' => 'Kab. Labuhan Batu Selatan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072700',  'nama_kabkota' => 'Kab. Nias Barat', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '072800',  'nama_kabkota' => 'Kab. Nias Utara', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076000',  'nama_kabkota' => 'Kota Medan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076100',  'nama_kabkota' => 'Kota Binjai', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076200',  'nama_kabkota' => 'Kota Tebing Tinggi', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076300',  'nama_kabkota' => 'Kota Pematang Siantar', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076400',  'nama_kabkota' => 'Kota Tanjung Balai', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076500',  'nama_kabkota' => 'Kota Sibolga', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076600',  'nama_kabkota' => 'Kota Padang Sidempuan', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '076700',  'nama_kabkota' => 'Kota Gunung Sitoli', 'id_provinsi' => '7', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080100',  'nama_kabkota' => 'Kab. Agam', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080200',  'nama_kabkota' => 'Kab. Pasaman', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080300',  'nama_kabkota' => 'Kab. Lima Puluh Koto', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080400',  'nama_kabkota' => 'Kab. Solok', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080500',  'nama_kabkota' => 'Kab. Padang Pariaman', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080600',  'nama_kabkota' => 'Kab. Pesisir Selatan', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080700',  'nama_kabkota' => 'Kab. Tanah Datar', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '080800',  'nama_kabkota' => 'Kab. Sawahlunto/ Sijunjung', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '081000',  'nama_kabkota' => 'Kab. Kepulauan Mentawai', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '081100',  'nama_kabkota' => 'Kab. Solok Selatan', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '081200',  'nama_kabkota' => 'Kab. Dharmas Raya', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '081300',  'nama_kabkota' => 'Kab. Pasaman Barat', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086000',  'nama_kabkota' => 'Kota Bukittinggi', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086100',  'nama_kabkota' => 'Kota Padang', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086200',  'nama_kabkota' => 'Kota Padang Panjang', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086300',  'nama_kabkota' => 'Kota Sawah Lunto', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086400',  'nama_kabkota' => 'Kota Solok', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086500',  'nama_kabkota' => 'Kota Payakumbuh', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '086600',  'nama_kabkota' => 'Kota Pariaman', 'id_provinsi' => '8', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090100',  'nama_kabkota' => 'Kab. Kampar', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090200',  'nama_kabkota' => 'Kab. Bengkalis', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090400',  'nama_kabkota' => 'Kab. Indragiri Hulu', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090500',  'nama_kabkota' => 'Kab. Indragiri Hilir', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090800',  'nama_kabkota' => 'Kab. Pelalawan', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '090900',  'nama_kabkota' => 'Kab. Rokan Hilir', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '091000',  'nama_kabkota' => 'Kab. Siak', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '091100',  'nama_kabkota' => 'Kab. Kuantan Singingi', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '091400',  'nama_kabkota' => 'Kab. Rokan Hulu', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '091500',  'nama_kabkota' => 'Kab. Kepulauan Meranti', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '096000',  'nama_kabkota' => 'Kota Pekanbaru', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '096200',  'nama_kabkota' => 'Kota Dumai', 'id_provinsi' => '9', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100100',  'nama_kabkota' => 'Kab. Batang Hari', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100200',  'nama_kabkota' => 'Kab. Bungo', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100300',  'nama_kabkota' => 'Kab. Sarolangun', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100400',  'nama_kabkota' => 'Kab. Tanjung Jabung Barat', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100500',  'nama_kabkota' => 'Kab. Kerinci', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100600',  'nama_kabkota' => 'Kab. Tebo', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100700',  'nama_kabkota' => 'Kab. Muaro Jambi', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100800',  'nama_kabkota' => 'Kab. Tanjung Jabung Timur', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '100900',  'nama_kabkota' => 'Kab. Merangin', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '106000',  'nama_kabkota' => 'Kota Jambi', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '106100',  'nama_kabkota' => 'Kab. Sungai Penuh', 'id_provinsi' => '10', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110100',  'nama_kabkota' => 'Kab. Musi Banyu Asin', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110200',  'nama_kabkota' => 'Kab. Ogan Komering Ilir', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110300',  'nama_kabkota' => 'Kab. Ogan Komering Ulu', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110400',  'nama_kabkota' => 'Kab. Muara Enim', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110500',  'nama_kabkota' => 'Kab. Lahat', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110600',  'nama_kabkota' => 'Kab. Musi Rawas', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110700',  'nama_kabkota' => 'Kab. Banyuasin', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110800',  'nama_kabkota' => 'Kab. Ogan Komering Ulu Timur', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '110900',  'nama_kabkota' => 'Kab. Ogan Komering Ulu Selatan', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '111000',  'nama_kabkota' => 'Kab. Ogan Ilir', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '111100',  'nama_kabkota' => 'Kab. Empat Lawang', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '111200',  'nama_kabkota' => 'Kab. Penukal Abab Lematang Ilir', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '111300',  'nama_kabkota' => 'Kab. Musi Rawas Utara', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '116000',  'nama_kabkota' => 'Kota Palembang', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '116100',  'nama_kabkota' => 'Kota Prabumulih', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '116200',  'nama_kabkota' => 'Kota Lubuk Linggau', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '116300',  'nama_kabkota' => 'Kota Pagar Alam', 'id_provinsi' => '11', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120100',  'nama_kabkota' => 'Kab. Lampung Selatan', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120200',  'nama_kabkota' => 'Kab. Lampung Tengah', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120300',  'nama_kabkota' => 'Kab. Lampung Utara', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120400',  'nama_kabkota' => 'Kab. Lampung Barat', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120500',  'nama_kabkota' => 'Kab. Tulang Bawang', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120600',  'nama_kabkota' => 'Kab. Tenggamus', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120700',  'nama_kabkota' => 'Kab. Lampung Timur', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120800',  'nama_kabkota' => 'Kab. Way Kanan', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '120900',  'nama_kabkota' => 'Kab. Pasawaran', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '121000',  'nama_kabkota' => 'Kab. Tulang Bawang Barat', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '121100',  'nama_kabkota' => 'Kab. Mesuji', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '121200',  'nama_kabkota' => 'Kab. Pringsewu', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '121300',  'nama_kabkota' => 'Kab. Pesisir Barat', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '126000',  'nama_kabkota' => 'Kota Bandar Lampung', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '126100',  'nama_kabkota' => 'Kota Metro', 'id_provinsi' => '12', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130100',  'nama_kabkota' => 'Kab. Sambas', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130200',  'nama_kabkota' => 'Kab. Pontianak', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130300',  'nama_kabkota' => 'Kab. Sanggau', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130400',  'nama_kabkota' => 'Kab. Sintang', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130500',  'nama_kabkota' => 'Kab. Kapuas Hulu', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130600',  'nama_kabkota' => 'Kab. Ketapang', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130800',  'nama_kabkota' => 'Kab. Bengkayang', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '130900',  'nama_kabkota' => 'Kab. Landak', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '131000',  'nama_kabkota' => 'Kab. Sekadau', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '131100',  'nama_kabkota' => 'Kab. Melawi', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '131200',  'nama_kabkota' => 'Kab. Kayong Utara', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '131300',  'nama_kabkota' => 'Kab. Kuburaya', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '136000',  'nama_kabkota' => 'Kota Pontianak', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '136100',  'nama_kabkota' => 'Kota Singkawang', 'id_provinsi' => '13', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140100',  'nama_kabkota' => 'Kab. Kapuas', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140200',  'nama_kabkota' => 'Kab. Barito Selatan', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140300',  'nama_kabkota' => 'Kab. Barito Utara', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140400',  'nama_kabkota' => 'Kab. Kotawaringin Timur', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140500',  'nama_kabkota' => 'Kab. Kotawaringin Barat', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140600',  'nama_kabkota' => 'Kab. Katingan', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140700',  'nama_kabkota' => 'Kab. Seruyan', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140800',  'nama_kabkota' => 'Kab. Sukamara', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '140900',  'nama_kabkota' => 'Kab. Lamandau', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '141000',  'nama_kabkota' => 'Kab. Gunung Mas', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '141100',  'nama_kabkota' => 'Kab. Pulang Pisau', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '141200',  'nama_kabkota' => 'Kab. Murung Raya', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '141300',  'nama_kabkota' => 'Kab. Barito Timur', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '146000',  'nama_kabkota' => 'Kota Palangka Raya', 'id_provinsi' => '14', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150100',  'nama_kabkota' => 'Kab. Banjar', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150200',  'nama_kabkota' => 'Kab. Tanah Laut', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150300',  'nama_kabkota' => 'Kab. Barito Kuala', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150400',  'nama_kabkota' => 'Kab. Tapin', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150500',  'nama_kabkota' => 'Kab. Hulu Sungai Selatan', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150600',  'nama_kabkota' => 'Kab. Hulu Sungai Tengah', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150700',  'nama_kabkota' => 'Kab. Hulu Sungai Utara', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150800',  'nama_kabkota' => 'Kab. Tabalong', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '150900',  'nama_kabkota' => 'Kab. Kota Baru', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '151000',  'nama_kabkota' => 'Kab. Balangan', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '151100',  'nama_kabkota' => 'Kab. Tanah Bumbu', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '156000',  'nama_kabkota' => 'Kota Banjarmasin', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '156100',  'nama_kabkota' => 'Kota Banjarbaru', 'id_provinsi' => '15', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160100',  'nama_kabkota' => 'Kab. Pasir', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160200',  'nama_kabkota' => 'Kab. Kutai Kartanegara', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160300',  'nama_kabkota' => 'Kab. Berau', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160400',  'nama_kabkota' => 'Kab. Bulongan', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160700',  'nama_kabkota' => 'Kab. Malinau', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160800',  'nama_kabkota' => 'Kab. Nunukan', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '160900',  'nama_kabkota' => 'Kab. Kutai Barat', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '161000',  'nama_kabkota' => 'Kab. Kutai Timur', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '161100',  'nama_kabkota' => 'Kab. Penajam Paser Utara', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '161200',  'nama_kabkota' => 'Kab. Mahakam Ulu', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '165400',  'nama_kabkota' => 'Kab. Tanah Tidung', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '166000',  'nama_kabkota' => 'Kota Samarinda', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '166100',  'nama_kabkota' => 'Kota Balikpapan', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '166200',  'nama_kabkota' => 'Kota Tarakan', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '166300',  'nama_kabkota' => 'Kota Bontang', 'id_provinsi' => '16', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170100',  'nama_kabkota' => 'Kab. Bolaang Mongondaw', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170200',  'nama_kabkota' => 'Kab. Minahasa', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170300',  'nama_kabkota' => 'Kab. Kep. Sangihe', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170400',  'nama_kabkota' => 'Kab. Kepulauan Talaud', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170500',  'nama_kabkota' => 'Kab. Minahasa Selatan', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170600',  'nama_kabkota' => 'Kab. Minahasa Utara', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170800',  'nama_kabkota' => 'Kab. Bolaang Mongondow Utara', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '170900',  'nama_kabkota' => 'Kab. Kepulauan Sitaro', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '171000',  'nama_kabkota' => 'Kab. Minahasa Tenggara', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '171100',  'nama_kabkota' => 'Kab. Bolaang Mongondaw Timur', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '171200',  'nama_kabkota' => 'Kab. Bolaang Mongondaw Selatan', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '176000',  'nama_kabkota' => 'Kota Manado', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '176100',  'nama_kabkota' => 'Kota Bitung', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '176200',  'nama_kabkota' => 'Kota Tomohon', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '176300',  'nama_kabkota' => 'Kota. Kotamobagu', 'id_provinsi' => '17', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180100',  'nama_kabkota' => 'Kab. Banggai Kepulauan', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180200',  'nama_kabkota' => 'Kab. Donggala', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180300',  'nama_kabkota' => 'Kab. Parigi Mautong', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180400',  'nama_kabkota' => 'Kab. Banggai', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180500',  'nama_kabkota' => 'Kab. Buol', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180600',  'nama_kabkota' => 'Kab. Toli-Toli', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180700',  'nama_kabkota' => 'Kab. Marowali', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180800',  'nama_kabkota' => 'Kab. Poso', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '180900',  'nama_kabkota' => 'Kab. Tojo Una-Una', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '181000',  'nama_kabkota' => 'Kab. Sigi', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '181100',  'nama_kabkota' => 'Kab. Banggai Laut', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '181200',  'nama_kabkota' => 'Kab. Morowali Utara', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '186000',  'nama_kabkota' => 'Kota Palu', 'id_provinsi' => '18', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190100',  'nama_kabkota' => 'Kab. Maros', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190200',  'nama_kabkota' => 'Kab. Pangkajene Kepulauan', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190300',  'nama_kabkota' => 'Kab. Gowa', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190400',  'nama_kabkota' => 'Kab. Takalar', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190500',  'nama_kabkota' => 'Kab. Jeneponto', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190600',  'nama_kabkota' => 'Kab. Barru', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190700',  'nama_kabkota' => 'Kab. Bone', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190800',  'nama_kabkota' => 'Kab. Wajo', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '190900',  'nama_kabkota' => 'Kab. Soppeng', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191000',  'nama_kabkota' => 'Kab. Bantaeng', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191100',  'nama_kabkota' => 'Kab. Bulukumba', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191200',  'nama_kabkota' => 'Kab. Sinjai', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191300',  'nama_kabkota' => 'Kab. Selayar', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191400',  'nama_kabkota' => 'Kab. Pinrang', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191500',  'nama_kabkota' => 'Kab. Sidenreng Rappang', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191600',  'nama_kabkota' => 'Kab. Enrekang', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191700',  'nama_kabkota' => 'Kab. Luwu', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '191800',  'nama_kabkota' => 'Kab. Tana Toraja', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '192400',  'nama_kabkota' => 'Kab. Luwu Utara', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '192600',  'nama_kabkota' => 'Kab. Luwu Timur', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '192700',  'nama_kabkota' => 'Kab. Toraja Utara', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '196000',  'nama_kabkota' => 'Kota Makassar', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '196100',  'nama_kabkota' => 'Kota Pare-Pare', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '196200',  'nama_kabkota' => 'Kota Palopo', 'id_provinsi' => '19', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200100',  'nama_kabkota' => 'Kab. Konawe', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200200',  'nama_kabkota' => 'Kab. Muna', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200300',  'nama_kabkota' => 'Kab. Buton', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200400',  'nama_kabkota' => 'Kab. Kolaka', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200500',  'nama_kabkota' => 'Kab. Konawe Selatan', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200600',  'nama_kabkota' => 'Kab. Wakatobi', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200700',  'nama_kabkota' => 'Kab. Bombana', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200800',  'nama_kabkota' => 'Kab. Kolaka Utara', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '200900',  'nama_kabkota' => 'Kab. Konawe Utara', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201000',  'nama_kabkota' => 'Kab. Buton Utara', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201100',  'nama_kabkota' => 'Kab. Kolaka Timur', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201200',  'nama_kabkota' => 'Kab. Konawe Kepulauan', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201300',  'nama_kabkota' => 'Kab. Muna Barat', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201400',  'nama_kabkota' => 'Kab. Buton Selatan', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '201600',  'nama_kabkota' => 'Kab. Buton Tengah', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '206000',  'nama_kabkota' => 'Kota Kendari', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '206100',  'nama_kabkota' => 'Kota Baubau', 'id_provinsi' => '20', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210100',  'nama_kabkota' => 'Kab. Maluku Tengah', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210200',  'nama_kabkota' => 'Kab. Maluku Tenggara', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210300',  'nama_kabkota' => 'Kab. Buru', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210400',  'nama_kabkota' => 'Kab. Maluku Tenggara Barat', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210500',  'nama_kabkota' => 'Kab. Seram Bagian Barat', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210600',  'nama_kabkota' => 'Kab. Seram Bagian Timur', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210700',  'nama_kabkota' => 'Kab. Kepulauan Aru', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210800',  'nama_kabkota' => 'Kab. Maluku Barat Daya', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '210900',  'nama_kabkota' => 'Kab. Buru Selatan', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '216000',  'nama_kabkota' => 'Kota Ambon', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '216100',  'nama_kabkota' => 'Kota. Tual', 'id_provinsi' => '21', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220100',  'nama_kabkota' => 'Kab. Buleleng', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220200',  'nama_kabkota' => 'Kab. Jembrana', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220300',  'nama_kabkota' => 'Kab. Tabanan', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220400',  'nama_kabkota' => 'Kab. Badung', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220500',  'nama_kabkota' => 'Kab. Gianyar', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220600',  'nama_kabkota' => 'Kab. Klungkung', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220700',  'nama_kabkota' => 'Kab. Bangli', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '220800',  'nama_kabkota' => 'Kab. Karang Asem', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '226000',  'nama_kabkota' => 'Kota Denpasar', 'id_provinsi' => '22', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230100',  'nama_kabkota' => 'Kab. Lombok Barat', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230200',  'nama_kabkota' => 'Kab. Lombok Tengah', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230300',  'nama_kabkota' => 'Kab. Lombok Timur', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230400',  'nama_kabkota' => 'Kab. Sumbawa', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230500',  'nama_kabkota' => 'Kab. Dompu', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230600',  'nama_kabkota' => 'Kab. Bima', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230700',  'nama_kabkota' => 'Kab. Sumbawa Barat', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '230800',  'nama_kabkota' => 'Kab. Lombok Utara', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '236000',  'nama_kabkota' => 'Kota Mataram', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '236100',  'nama_kabkota' => 'Kota Bima', 'id_provinsi' => '23', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240100',  'nama_kabkota' => 'Kab. Kupang', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240300',  'nama_kabkota' => 'Kab. Timor Tengah Selatan', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240400',  'nama_kabkota' => 'Kab. Timor Tengah Utara', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240500',  'nama_kabkota' => 'Kab. Belu', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240600',  'nama_kabkota' => 'Kab. Alor', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240700',  'nama_kabkota' => 'Kab. Flores Timur', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240800',  'nama_kabkota' => 'Kab. Sikka', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '240900',  'nama_kabkota' => 'Kab. Ende', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241000',  'nama_kabkota' => 'Kab. Ngada', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241100',  'nama_kabkota' => 'Kab. Manggarai', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241200',  'nama_kabkota' => 'Kab. Sumba Timur', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241300',  'nama_kabkota' => 'Kab. Sumba Barat', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241400',  'nama_kabkota' => 'Kab. Lembata', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241500',  'nama_kabkota' => 'Kab. Rote-Ndao', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241600',  'nama_kabkota' => 'Kab. Manggarai Barat', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241700',  'nama_kabkota' => 'Kab. Nagakeo', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241800',  'nama_kabkota' => 'Kab. Sumba Tengah', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '241900',  'nama_kabkota' => 'Kab. Sumba Barat Daya', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '242000',  'nama_kabkota' => 'Kab. Manggarai Timur', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '242100',  'nama_kabkota' => 'Kab. Sabu Raijua', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '242200',  'nama_kabkota' => 'Kab. Malaka', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '246000',  'nama_kabkota' => 'Kota Kupang', 'id_provinsi' => '24', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250100',  'nama_kabkota' => 'Kab. Jayapura', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250200',  'nama_kabkota' => 'Kab. Biak Numfor', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250300',  'nama_kabkota' => 'Kab. Yapen Waropen', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250700',  'nama_kabkota' => 'Kab. Merauke', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250800',  'nama_kabkota' => 'Kab. Jayawijaya', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '250900',  'nama_kabkota' => 'Kab. Nabire', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251000',  'nama_kabkota' => 'Kab. Paniai', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251100',  'nama_kabkota' => 'Kab. Puncak Jaya', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251200',  'nama_kabkota' => 'Kab. Mimika', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251300',  'nama_kabkota' => 'Kab. Boven Digoel', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251400',  'nama_kabkota' => 'Kab. Mappi', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251500',  'nama_kabkota' => 'Kab. Asmat', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251600',  'nama_kabkota' => 'Kab. Yahukimo', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251700',  'nama_kabkota' => 'Kab. Pegunungan Bintang', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251800',  'nama_kabkota' => 'Kab. Tolikara', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '251900',  'nama_kabkota' => 'Kab. Sarmi', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '252000',  'nama_kabkota' => 'Kab. Keerom', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '252600',  'nama_kabkota' => 'Kab. Waropen', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '252700',  'nama_kabkota' => 'Kab. Supiori', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '252800',  'nama_kabkota' => 'Kab. Memberamo Raya', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '252900',  'nama_kabkota' => 'Kab. Nduga', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253000',  'nama_kabkota' => 'Kab. Lanny Jaya', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253100',  'nama_kabkota' => 'Kab. Membramo Tengah', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253200',  'nama_kabkota' => 'Kab. Yalimo', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253300',  'nama_kabkota' => 'kab. Puncak', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253400',  'nama_kabkota' => 'Kab. Dogiyai', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253500',  'nama_kabkota' => 'Kab. Deiyai', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '253600',  'nama_kabkota' => 'Kab. Intan Jaya', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '256000',  'nama_kabkota' => 'Kota Jayapura', 'id_provinsi' => '25', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260100',  'nama_kabkota' => 'Kab. Bengkulu Utara', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260200',  'nama_kabkota' => 'Kab. Rejang Lebong', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260300',  'nama_kabkota' => 'Kab. Bengkulu Selatan', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260400',  'nama_kabkota' => 'Kab. Muko-muko', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260500',  'nama_kabkota' => 'Kab. Kepahiang', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260600',  'nama_kabkota' => 'Kab. Lebong', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260700',  'nama_kabkota' => 'Kab. Kaur', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260800',  'nama_kabkota' => 'Kab. Seluma', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '260900',  'nama_kabkota' => 'Kab. Bengkulu Tengah', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '266000',  'nama_kabkota' => 'Kota Bengkulu', 'id_provinsi' => '26', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270100',  'nama_kabkota' => 'Kab. Pulau Taliabu', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270200',  'nama_kabkota' => 'Kab. Halmahera Tengah', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270300',  'nama_kabkota' => 'Kab. Halmahera Barat', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270400',  'nama_kabkota' => 'Kab. halmahera Utara', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270500',  'nama_kabkota' => 'Kab. Halmahera Selatan', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270600',  'nama_kabkota' => 'Kab. Halmahera Timur', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270700',  'nama_kabkota' => 'Kab. Kepulauan Sula', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '270800',  'nama_kabkota' => 'Kab. Kepulauan Morotai', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '276000',  'nama_kabkota' => 'Kota Ternate', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '276100',  'nama_kabkota' => 'Kota Tidore Kepulauan', 'id_provinsi' => '27', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '280100',  'nama_kabkota' => 'Kab. Pandeglang', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '280200',  'nama_kabkota' => 'Kab. Lebak', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '280300',  'nama_kabkota' => 'Kab. Tangerang', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '280400',  'nama_kabkota' => 'Kab. Serang', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '286000',  'nama_kabkota' => 'Kota Cilegon', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '286100',  'nama_kabkota' => 'Kota Tangerang', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '286200',  'nama_kabkota' => 'Kota Serang', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '286300',  'nama_kabkota' => 'Kota tangerang Selatan', 'id_provinsi' => '28', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290100',  'nama_kabkota' => 'Kab. Bangka', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290200',  'nama_kabkota' => 'Kab. Belitung', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290300',  'nama_kabkota' => 'Kab. Bangka Tengah', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290400',  'nama_kabkota' => 'Kab. Bangka Barat', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290500',  'nama_kabkota' => 'Kab. Bangka Selatan', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '290600',  'nama_kabkota' => 'Kab. Belitung Timur', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '296000',  'nama_kabkota' => 'Kota Pangkalpinang', 'id_provinsi' => '29', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '300100',  'nama_kabkota' => 'Kab. Boalemo', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '300200',  'nama_kabkota' => 'Kab. Gorontalo', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '300300',  'nama_kabkota' => 'Kab. Pohuwato', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '300400',  'nama_kabkota' => 'Kab. Bone Bolango', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '300500',  'nama_kabkota' => 'Kab. Gorontalo Utara', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '306000',  'nama_kabkota' => 'Kota Gorontalo', 'id_provinsi' => '30', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '310100',  'nama_kabkota' => 'Kab. Bintan', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '310200',  'nama_kabkota' => 'Kab. Karimun', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '310300',  'nama_kabkota' => 'Kab. Natuna', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '310400',  'nama_kabkota' => 'Kab. Lingga', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '310500',  'nama_kabkota' => 'Kab. Kepulauan Anambas', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '316000',  'nama_kabkota' => 'Kota Batam', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '316100',  'nama_kabkota' => 'Kota Tanjungpinang', 'id_provinsi' => '31', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320100',  'nama_kabkota' => 'Kab. Fak-Fak', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320200',  'nama_kabkota' => 'Kab. Kaimana', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320300',  'nama_kabkota' => 'Kab. Teluk Wondama', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320400',  'nama_kabkota' => 'Kab. Teluk Bintuni', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320500',  'nama_kabkota' => 'Kab. Manokwari', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320600',  'nama_kabkota' => 'Kab. Sorong Selatan', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320700',  'nama_kabkota' => 'Kab. Sorong', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320800',  'nama_kabkota' => 'Kab. Raja Ampat', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '320900',  'nama_kabkota' => 'Kab. Tambrauw', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '321000',  'nama_kabkota' => 'Kab. Maybrat', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '321100',  'nama_kabkota' => 'Kab. Pegunungan Arfak', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '321200',  'nama_kabkota' => 'Kab. Manokwari Selatan', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '326000',  'nama_kabkota' => 'Kota Sorong', 'id_provinsi' => '32', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330100',  'nama_kabkota' => 'Kab. Mamuju', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330200',  'nama_kabkota' => 'Kab. Mamuju Utara', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330300',  'nama_kabkota' => 'Kab. Polewali Mamasa', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330400',  'nama_kabkota' => 'Kab. Mamasa', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330500',  'nama_kabkota' => 'Kab. Majene', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '330600',  'nama_kabkota' => 'Kab. Mamuju Tengah', 'id_provinsi' => '33', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '340100',  'nama_kabkota' => 'Kab. Malinau', 'id_provinsi' => '34', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '340200',  'nama_kabkota' => 'Kab. Bulungan', 'id_provinsi' => '34', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '340300',  'nama_kabkota' => 'Kab. Tana Tidung', 'id_provinsi' => '34', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '340500',  'nama_kabkota' => 'Kab. Nunukan', 'id_provinsi' => '34', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '346000',  'nama_kabkota' => 'Kota Tarakan', 'id_provinsi' => '34', 'created_at' => now(), 'updated_at' => now() ],
[ 'kd_kabkota' => '999999',  'nama_kabkota' => 'Luar Negeri', 'id_provinsi' => '35', 'created_at' => now(), 'updated_at' => now() ],
        ];
        foreach($array as $key => $row){
            DB::table('kabkotas')->insert($row);
        }

    }
}
